### PR TITLE
Update auto build, turn on lint and make lint pass.

### PR DESCRIPTION
**Pull request by tannewt**
This changes the attribute seaLevelhPa to sea_level_pressure to
match python naming standards.

### CODE REVIEW

**Comment by tdicola** [comment]
FYI this is an API breaking change to modify the property name.  Be sure to also update the guide here and its written up example of usage (including new screenshots): https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/downloads?view=all#circuitpython-test  If you're changing other libraries and their properties consult their guides as many of them are written with the current properties.  IMHO I would separate out making API breaking changes into separate pulls and releases so it's more obvious to someone that the library changed in a breaking way.

**Comment by tannewt** [comment]
Ok, will do. Thanks for the heads up.

I've got a PR (https://github.com/adafruit/cookiecutter-adafruit-circuitpython/pull/6) out to update cookiecutter so any new libraries will break upon misnaming and other lint errors.

@jwcooper can we get a REPL (green on black or similar) styled code block so that we don't need to use immutable screenshots?

**Comment by tdicola** [comment]
Double check with @ladyada as we explicitly changed to add screenshots vs. code blocks for guides.  If you have mu and it works that would be even better and preferred (my version sadly still doesn't work).

**Comment by tannewt** [comment]
@tdicola What was the motivation?

**Comment by tdicola** [comment]
I assume to show people exactly what to expect, this was an example of the preferred output: https://learn.adafruit.com/adafruit-pcf8523-real-time-clock/rtc-with-circuitpython#setting-the-time

**Review by kattni — APPROVED** [review]
Everything looks good! Holding off on merging until library is tested with sensor.

**Comment by ladyada** [comment]
yep - screenshots keep us honest :D

**Comment by kattni** [comment]
Tested by @jerryneedell successfully. Merging.

**Pull request merged**
